language: rust

rust:
  - nightly

addons:
  apt:
    packages:
      - gcc-arm-none-eabi

script:
  - rustup target add thumbv6m-none-eabi
  - cargo build --verbose --target=thumbv6m-none-eabi --features="rt"
  - cargo test --verbose

cache: cargo
