language: rust

rust:
  - nightly

addons:
  apt:
    packages:
      - gcc-arm-none-eabi

script:
  - rustup target add thumbv6m-none-eabi
  - cargo test --verbose --features="compiletest"
  - ./scripts/build-examples.sh
