language: rust

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - gcc-arm-none-eabi

install:
  - rustup target add thumbv6m-none-eabi
  - rustup component add rustfmt

script:
  - |
    cargo fmt -- --check &&
    ./scripts/build.sh
