[package]
name    = "lpc82x-hal"
version = "0.1.1-dev"
authors = ["Hanno Braun <hanno@braun-robotics.com>"]

description   = "Hardware Abstraction Layer (HAL) for the NXP LPC82x series of ARM Cortex-M0+ microcontroller"
documentation = "https://docs.rs/lpc82x-hal"
repository    = "https://github.com/braun-robotics/rust-lpc82x-hal"
license       = "0BSD"
readme        = "README.md"
categories    = ["embedded", "hardware-support", "no-std"]
keywords      = ["arm", "cortex-m", "nxp", "lpc", "embedded-hal-impl"]


[badges]
maintenance = { status = "actively-developed" }
travis-ci   = { repository = "braun-robotics/rust-lpc82x-hal" }


[dependencies]
cortex-m     = "0.5"
embedded-hal = { version = "0.2", features = ["unproven"] }
lpc82x       = "0.4"
nb           = "0.1.1"
void         = { version = "1", default-features = false }

[dev-dependencies]
panic-abort = "0.1"


[features]
rt = ["lpc82x/rt"]


[[example]]
name              = "gpio"
required-features = ["rt"]

[[example]]
name              = "usart"
required-features = ["rt"]


[package.metadata.release]
pre-release-commit-message = "chore: Release version {{version}}"
pro-release-commit-message = "chore: Bump version to {{version}}"
tag-prefix                 = "v"
tag-message                = "Version {{version}}"
dev-version-ext            = "dev"
